### ISSUE TITLE
Escape all angle brackets for full `mdx` support

### ISSUE THREAD

**Issue by ifiokjr** [tgreyuk/typedoc-plugin-markdown#141]
### Description

Thanks for all your work maintaining these plugins. Not only is it really useful, but the markdown plugin builds much faster as well.

I've had a look at prior work in #136 #128 #119 and others. 

However, I'm facing the issue when building with `docusaurus` that neither types nor angle brackets are properly escaped. 

The issue can be seen in [this build failure](https://github.com/remirror/remirror/pull/619/checks?check_run_id=1058210345). It seems there are several places where tags are not being escaped. 

[This code](https://github.com/remirror/remirror/blob/1fd87e9a71ba9b683334cbeefdbec4d457a6f4e7/packages/jest-prosemirror/src/jest-prosemirror-nodes.ts#L238-L239) breaks the Markdown implementation since HTML tags are not properly escaped. 

![2020-09-01 20 55 30](https://user-images.githubusercontent.com/1160934/91900051-fac94c80-ec95-11ea-868b-d5e812f22d98.gif)

### Steps

To replicate the same issue:

- Checkout the remirror codebase 

	```bash
	git clone https://github.com/remirror/remirror
	git checkout typedoc
	```
- Install the dependencies with `pnpm`. To setup `pnpm ` run `npm i -g pnpm`. 
- Run the build `pnpm run build:docs` and see the failures. 

This might take a while to build. If you'd like to see the failures faster you can edit the `docusaurus` config located at `support/website/docusaurus.config.js` and remove the `if (process.env.NODE_ENV === 'production')` conditional. Then run `pnpm run docs`.

remirror/remirror/pull/619

[![image](https://user-images.githubusercontent.com/1160934/91901349-00c02d00-ec98-11ea-8e81-fa7ff19cc71e.png)](https://github.com/remirror/remirror/pull/619/checks?check_run_id=1058210345)

**Comment by ifiokjr** [comment]
I'm happy to create a PR if given a small pointer in the right direction.

**Comment by tgreyuk** [comment]
@ifiokjr Thanks for the super detailed description. I have run the code against the updated docusaurus-plugin-typedoc **0.0.3** and it compiles without error. For consistency have replaced the angle brackets with pointed angles but will have a think if html escape would be better long term.

I am currently refactoring and fixing some stuff so let me know if you see anything that could work better.

**Comment by ifiokjr** [comment]
Thanks so much for the super quick fix. I just had the chance to test it out and it works perfectly 👍  

I'll push an update soon.

**Comment by tgreyuk** [comment]
FYI your project repo has exposed a few bugs that you have probably noticed. I am going through them now and hope to have an update in a few days....

**Comment by B4nan** [comment]
Looks like this is still broken for a bit more complex signatures:

```
Failed to compile
./docs/api/classes/unitofwork.md
SyntaxError: /usr/local/var/www/b4nan/mikro-orm/docs/docs/api/classes/unitofwork.md: Expected corresponding JSX closing tag for <AnyEntity> (522:72)

  520 | <td parentName="tr" {...{"align":null}}><inlineCode parentName="td">{`visited`}</inlineCode></td>
  521 | <td parentName="tr" {...{"align":null}}>{`WeakSet`}{`<`}<a parentName="td" {...{"href":"/docs/next/api/globals#anyentity"}}>{`AnyEntity`}</a>{`<`}{`any>>`}</td>
> 522 | <td parentName="tr" {...{"align":null}}>{`new WeakSet`}<AnyEntity>{`()`}</td>
      |                                                                         ^
  523 | </tr>
  524 | </tbody>
  525 | </table>
```

The generated markdown looks like this:

```md
#### Parameters:

Name | Type | Default value |
------ | ------ | ------ |
`entity` | T | - |
`visited` | WeakSet&#60;[AnyEntity](../globals.md#anyentity)&#60;any>> | new WeakSet<AnyEntity>() |
```

The method signature is:

```ts
private findNewEntities<T extends AnyEntity<T>>(entity: T, visited = new WeakSet<AnyEntity>()): void {
```

Using latest version (via `docusaurus-plugin-typedoc`):

```
"typedoc": "^0.19.2",
"typedoc-plugin-markdown": "^3.0.10"
```

**Comment by tgreyuk** [comment]
@B4nan thanks default values not being escaped - should be fixed in typedoc-plugin-markdown@3.0.11

As for 404 assuming that the docs are being published to docs/api the index.md file should contain `slug: "/{{outDir}}"` - if that is not happening in your use-case would need to look into it further...

**Comment by B4nan** [comment]
Thanks for the fast fix, confirmed it builds now. I do have `slug: "/api"` in the front matter of `/docs/api/index.md`, but still I can't get to that page. 

```
---
id: "index"
title: "@mikro-orm/core"
slug: "/api"
sidebar_label: "README"
hide_title: true
---
```

The rest of the file are contents of my `README.md`. Docusaurus config [here](https://github.com/mikro-orm/mikro-orm/blob/master/docs/docusaurus.config.js), plus:

```
  plugins: [
    [
      'docusaurus-plugin-typedoc',
      {
        // Plugin options
        inputFiles: ['../packages/core/src'],

        // TypeDoc options (see typedoc --help)
        mode: 'file',
        target: 'ES2017',
        moduleResolution: 'node',
        ignoreCompilerErrors: true,
        tsconfig: '../packages/core/tsconfig.json',
      },
    ],
  ],
```

Tried to update docusaurus to `2.0.0-alpha.66` but no luck, still the same.

**Comment by tgreyuk** [comment]
ok thanks - i will try and work out why this would happen...

**Comment by B4nan** [comment]
Pushed it to this branch so you can take a look at the full project (docusaurus is in the `docs` folder, so `cd docs && yarn && yarn start` to run it):

https://github.com/mikro-orm/mikro-orm/tree/typedoc

**Comment by tgreyuk** [comment]
@B4nan so I think this is to do with your versioned docs - if you navigate to `docs/next/api` then the doc is available (as I assume this picks up from root). Otherwise it seems to be looking in `versioned_docs` where the api folder hasn't been created.

**Comment by B4nan** [comment]
Oh right, I see. Because `docs/docs` is actually folder for next version, not the last stable that lives on `/docs` url. In fact it makes sense, as it build the apidoc based on master where the latest code lives, not based on the version. So when I ship new docusaurus docs version, it would be moved to the versioned_docs folder and be accessible on the `/docs/api`.

**Comment by tgreyuk** [comment]
Ok makes sense. Let me know if you come across anything else..
